title: EduVis Workshop
logo: /assets/img/logo_eduvis.png
description: IEEE VIS Workshop on Visualization Education, Literacy, and Activities
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
